import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const currentYear = new Date().getFullYear();

const resources = {
  en: {
    translation: {
      nav: { home: 'Home', about: 'About', skills: 'Skills', projects: 'Projects', contact: 'Contact' },
      home: {
        greeting: "Hello, I'm",
        name: 'Faridun Abdurazakov',
        title: 'Frontend Web Developer',
        description: 'I craft modern, responsive web interfaces with React and clean CSS. Passionate about pixel-perfect UI/UX design and smooth animations.',
        hireMe: 'Hire Me',
        exploreWork: 'Explore Work',
        profileAlt: 'Available for work',
        stat1Value: '1+', stat1Label: 'Year Experience',
        stat2Value: '10+', stat2Label: 'Projects Built',
        stat3Value: '100%', stat3Label: 'Commitment',
        bioTitle: 'Who I Am',
        bioText: "I'm Faridun Abdurazakov \u2014 a Frontend Web Developer based in Uzbekistan with 1 year of hands-on experience. I specialize in building beautiful, responsive user interfaces with React, HTML5, CSS3, and Tailwind CSS. I'm passionate about clean code, smooth animations, and creating web experiences that feel native on every device.",
        roles: ['Frontend Developer', 'React Enthusiast', 'UI/UX Designer', 'CSS Artisan'],
        philosophy: ['Pixel-perfect UI/UX design', 'Clean, maintainable code', 'Mobile-first responsive approach'],
        numbersTitle: 'By the Numbers',
        numbersSubtitle: 'A snapshot of my frontend journey so far',
        metrics: [
          { value: '10+', label: 'Projects Built', desc: 'From landing pages to full React apps' },
          { value: '7+', label: 'Technologies', desc: 'React, JS, HTML, CSS, Tailwind, Git, Firebase' },
          { value: '500+', label: 'Code Hours', desc: 'Dedicated practice and real-world projects' },
          { value: '100%', label: 'Commitment', desc: 'Every pixel crafted with intention' },
        ],
        featuredTitle: 'Featured Work',
        featuredSubtitle: 'A preview of my most recent projects',
        viewAll: 'View All Projects',
        capabilitiesTitle: 'What I Do',
        capabilitiesSubtitle: 'Core frontend capabilities I bring to every project',
        capabilities: [
          { title: 'Modern Web Layouts', desc: 'Semantic HTML5 with Flexbox, Grid, and CSS custom properties for pixel-perfect structures.' },
          { title: 'Responsive UI Design', desc: 'Mobile-first Tailwind CSS components tested across phones, tablets, and desktops.' },
          { title: 'Animation Tweaks', desc: 'Framer Motion transitions, CSS keyframes, and micro-interactions that feel native.' },
        ],
        workflowTitle: 'My Workflow',
        workflowSubtitle: 'How I go from idea to deployed application',
        workflow: [
          { step: '01', title: 'Plan', desc: 'Component structure & props' },
          { step: '02', title: 'Build', desc: 'React + Tailwind assembly' },
          { step: '03', title: 'Animate', desc: 'Framer Motion transitions' },
          { step: '04', title: 'Test', desc: 'Cross-device responsiveness' },
          { step: '05', title: 'Ship', desc: 'Optimize & deploy' },
        ],
        ctaTitle: "Let's Build Something Together",
        ctaText: "I'm always open to discussing new projects, creative ideas, or opportunities to be part of your vision. Drop me a message and let's start a conversation.",
        ctaPrimary: 'Get in Touch',
        ctaSecondary: 'Message on Telegram',
        featuredProjects: [
          { name: 'Portfolio v2', tags: ['React', 'Tailwind', 'Framer Motion'] },
          { name: 'Weather Dashboard', tags: ['React', 'Chart.js', 'API'] },
          { name: 'Task Manager', tags: ['React', 'DnD', 'LocalStorage'] },
        ],
      },
      about: {
        title: 'About Me',
        subtitle: 'My journey, philosophy, and passion for frontend development',
        bioTitle: 'My Story',
        bioText1: "I'm Faridun Abdurazakov, a Frontend Web Developer with 1 year of dedicated experience in crafting modern web interfaces. My journey began with curiosity about how beautiful websites are built, and it quickly evolved into a deep passion for React, responsive design, and creating pixel-perfect UIs that delight users.",
        bioText2: "My philosophy centers on writing clean, maintainable code while keeping the end user at the heart of every design decision. I believe great frontend work is about the details \u2014 smooth transitions, accessible layouts, and interfaces that feel intuitive and alive.",
        bioText3: "Every day I'm learning something new \u2014 exploring modern CSS techniques, React patterns, and animation libraries. I'm committed to growing as a frontend developer and contributing to the web community.",
        timelineTitle: 'My Journey',
        timelineSubtitle: 'From my first HTML tag to modern React applications',
        timeline: [
          { period: `${currentYear} \u2014 Present`, role: 'Frontend Web Developer', company: 'Independent / Freelance', desc: 'Building modern web interfaces with React, Tailwind CSS, and Framer Motion. Focused on responsive UI/UX design, component architecture, and performance optimization.' },
          { period: `2023 \u2014 ${currentYear}`, role: 'Frontend Learner & Builder', company: 'Self-Taught Journey', desc: 'Completed focused studies in HTML5, CSS3, JavaScript, and React. Built multiple personal projects to master responsive design and modern frontend patterns.' },
          { period: '2023', role: 'Started Coding Journey', company: 'First Steps', desc: 'Wrote my first lines of HTML and CSS. Built simple static pages and discovered my passion for turning designs into real, interactive web pages.' },
        ],
        statsTitle: 'By the Numbers',
        stat1: { value: '1+', label: 'Year of Experience' },
        stat2: { value: '10+', label: 'Projects Completed' },
        stat3: { value: '7+', label: 'Technologies Used' },
        stat4: { value: '100%', label: 'Dedication' },
        principlesTitle: 'Development Principles',
        principlesSubtitle: 'The values that guide every project I build',
        principles: [
          { title: 'Pixel-Perfect UI', desc: 'Every element is measured, aligned, and polished. I obsess over spacing, typography, and visual hierarchy to create interfaces that feel intentional and refined.' },
          { title: 'Clean Code', desc: 'Readable, maintainable, and well-structured components. I write code that other developers (and my future self) can understand and extend without friction.' },
          { title: 'Mobile First', desc: 'Every interface starts on the smallest screen and scales up. This ensures a native, fluid experience whether on a phone, tablet, or desktop monitor.' },
        ],
        toolsTitle: 'Tools I Rely On',
        toolsSubtitle: 'The technologies that power my daily workflow',
        tools: [
          { name: 'React.js', icon: '\u269B\uFE0F', desc: 'Component-based UI library for building interactive interfaces' },
          { name: 'Tailwind CSS', icon: '\uD83C\uDFA8', desc: 'Utility-first CSS framework for rapid, consistent styling' },
          { name: 'Git & GitHub', icon: '\uD83D\uDD27', desc: 'Version control and collaborative code management' },
          { name: 'Vite', icon: '\u26A1', desc: 'Next-generation frontend build tool with instant HMR' },
          { name: 'Firebase', icon: '\uD83D\uDD25', desc: 'Backend-as-a-service for authentication and Firestore database' },
          { name: 'VS Code', icon: '\uD83D\uDCBB', desc: 'Primary code editor with optimized extensions' },
        ],
        interestsTitle: 'Beyond the Code',
        interestsSubtitle: 'What inspires and motivates me outside of development',
        interests: [
          { title: 'UI Design Inspiration', desc: "Exploring Dribbble, Behance, and Apple's design system for fresh interface ideas and interaction patterns." },
          { title: 'Tech Trends', desc: 'Following the latest in React Server Components, CSS container queries, and the evolving JavaScript ecosystem.' },
          { title: 'Continuous Learning', desc: "Every day is an opportunity to learn something new \u2014 whether it's a CSS trick, a React pattern, or a design principle." },
        ],
        valuesTitle: 'What I Stand For',
        valuesSubtitle: 'The principles that define how I approach every project',
        values: [
          { title: 'Quality Over Quantity', desc: "I'd rather build one exceptional project than ten mediocre ones. Every line of code gets my full attention and care." },
          { title: 'Continuous Learning', desc: 'The web evolves fast. I stay current by reading docs, watching tutorials, and building side projects that push my skills forward.' },
          { title: 'Attention to Detail', desc: 'The difference between good and great is in the details \u2014 smooth transitions, perfect spacing, and intuitive user flows.' },
        ],
        ctaTitle: 'Want to Connect?',
        ctaText: "I'm always happy to chat about frontend development, new projects, or just say hello.",
        ctaButton: 'Send a Message',
      },
      skills: {
        title: 'Skills & Tech Stack',
        subtitle: 'Frontend technologies I use to bring ideas to life',
        frontend: 'Frontend Development',
        tools: 'Tools & Workflow',
        skillDetails: [
          { title: 'React.js Mastery', level: 80, topics: ['Functional Components & Hooks', 'useState, useEffect, useContext', 'React Router for navigation', 'Framer Motion animations', 'Component composition patterns', 'Props drilling & state lifting'] },
          { title: 'Tailwind CSS & Styling', level: 88, topics: ['Utility-first CSS workflow', 'Responsive design (mobile-first)', 'Flexbox & CSS Grid layouts', 'Custom theming with CSS variables', 'Dark mode implementation', 'Glassmorphism & backdrop effects'] },
          { title: 'JavaScript ES6+', level: 75, topics: ['Arrow functions & destructuring', 'Template literals & spread operator', 'Promises & async/await', 'Array methods (map, filter, reduce)', 'Modules (import/export)', 'DOM manipulation & events'] },
          { title: 'HTML5 & CSS3 Standards', level: 90, topics: ['Semantic HTML elements', 'CSS animations & transitions', 'CSS custom properties', 'Form validation & accessibility', 'Media queries & breakpoints', 'CSS transforms & keyframes'] },
        ],
        devToolsTitle: 'Developer Tools',
        devToolsSubtitle: 'The tools that power my daily development workflow',
        devTools: [
          { name: 'VS Code', icon: '\uD83D\uDCBB', desc: 'Primary editor with Prettier, ESLint, Tailwind IntelliSense, and GitLens extensions.', level: 'Power User' },
          { name: 'Git & GitHub', icon: '\uD83D\uDD27', desc: 'Version control with branching strategies, pull requests, and collaborative workflows.', level: 'Daily Use' },
          { name: 'Vite', icon: '\u26A1', desc: 'Lightning-fast build tool with instant HMR for rapid development cycles.', level: 'Build Tool' },
          { name: 'npm', icon: '\uD83D\uDCE6', desc: 'Package management, script automation, and dependency management.', level: 'Essential' },
          { name: 'Chrome DevTools', icon: '\uD83D\uDD0D', desc: 'Performance profiling, responsive debugging, and network analysis.', level: 'Debugging' },
          { name: 'Figma', icon: '\uD83C\uDFA8', desc: 'Design-to-code workflow, inspecting assets, and understanding design specs.', level: 'Design' },
        ],
        firebaseTitle: 'Firebase Integration',
        firebaseSubtitle: 'Backend-as-a-service for seamless data handling',
        firebaseSubheading: 'Firebase Firestore',
        firebaseFeatures: [
          { title: 'Firestore Database', desc: 'Document-based NoSQL database for storing contact form submissions, user data, and application state in real-time.' },
          { title: 'Contact Form Integration', desc: 'Form submissions are saved directly to the Firestore messages collection with timestamps for tracking and response.' },
          { title: 'Real-time Updates', desc: 'Firestore provides real-time synchronization, enabling instant data reflection across connected clients.' },
        ],
        uiuxTitle: 'UI/UX Design Practices',
        uiuxSubtitle: 'How I approach visual design and user experience',
        uiux: [
          { title: 'Figma to Code', desc: 'Translating design mockups into pixel-perfect React components with accurate spacing, typography, and color.' },
          { title: 'Glassmorphism Design', desc: 'Creating frosted glass effects with backdrop-blur, semi-transparent backgrounds, and subtle border highlights.' },
          { title: 'Mobile Responsiveness', desc: 'Testing and optimizing layouts across phones, tablets, and desktops using Tailwind responsive utilities.' },
          { title: 'Micro-Interactions', desc: 'Adding hover effects, loading states, and transition animations that make interfaces feel alive and responsive.' },
        ],
        roadmapTitle: 'Learning Roadmap',
        roadmapSubtitle: "Technologies I'm currently exploring and planning to learn",
        roadmap: [
          { tech: 'TypeScript', status: 'Learning', desc: 'Adding type safety to React projects for better developer experience and fewer runtime errors.' },
          { tech: 'Next.js', status: 'Exploring', desc: 'Server-side rendering, static generation, and the full-stack React framework for production apps.' },
          { tech: 'React Native', status: 'Planned', desc: 'Building native mobile applications using familiar React patterns and components.' },
          { tech: 'Testing (Jest)', status: 'Planned', desc: 'Unit and integration testing for reliable, maintainable frontend codebases.' },
        ],
      },
      projects: {
        title: 'Projects',
        subtitle: 'A curated selection of my frontend work and experiments',
        viewDemo: 'Live Demo',
        viewRepo: 'Source Code',
        featured: 'Featured',
        all: 'All',
        filter1: 'Web Apps',
        filter2: 'Mobile',
        filter3: 'Open Source',
        project1: { name: 'Portfolio v2', category: 'web', description: 'My personal portfolio built with React, Tailwind CSS, and Framer Motion. Features iOS glassmorphism design, dark mode, and multilingual support.', tags: ['React', 'Tailwind', 'Framer Motion'] },
        project2: { name: 'Weather Dashboard', category: 'web', description: 'A clean, responsive weather dashboard with 7-day forecasts, interactive maps, and beautiful data visualizations.', tags: ['React', 'Chart.js', 'API'] },
        project3: { name: 'Task Manager App', category: 'web', description: 'A minimal task management app with drag-and-drop, categories, and local storage persistence.', tags: ['React', 'DnD', 'LocalStorage'] },
        project4: { name: 'E-Commerce UI', category: 'web', description: 'Responsive e-commerce landing page with product cards, shopping cart, and sleek checkout flow.', tags: ['React', 'CSS3', 'Responsive'] },
        project5: { name: 'Chat App UI', category: 'mobile', description: 'Mobile-first chat application interface with message bubbles, typing indicators, and smooth transitions.', tags: ['React', 'Mobile UI', 'Animations'] },
        project6: { name: 'CSS Art Gallery', category: 'opensource', description: 'A collection of creative CSS-only art pieces and animations, open-sourced for the community.', tags: ['CSS3', 'Animations', 'Open Source'] },
        caseStudyTitle: 'Case Study',
        caseStudySubtitle: 'A deep look at the architecture behind',
        caseStudy: {
          name: 'Portfolio v2',
          stack: ['React', 'Tailwind CSS', 'Framer Motion', 'Firebase', 'i18next'],
          features: ['iOS glassmorphism design system', 'Dark/Light mode with persistence', '3-language support (EN/UZ/RU)', 'Firebase Firestore contact form', 'Animated page transitions', 'Fully responsive mobile-first layout'],
          architecture: 'Built as a single-page React application with React Router for multi-page navigation. Components are organized into /components for reusable UI elements, /pages for route-level views, and /context for global state management (theme and language).',
        },
        openSourceTitle: 'Open Source',
        openSourceSubtitle: 'Contributions and community projects',
        openSource: [
          { name: 'CSS Art Gallery', desc: 'Creative CSS-only art pieces and animations for the community.', stars: 24, lang: 'CSS' },
          { name: 'Tailwind Glass Utils', desc: 'Reusable glassmorphism utility classes for Tailwind CSS projects.', stars: 18, lang: 'CSS' },
          { name: 'React Hook Snippets', desc: 'Common custom React hooks for form handling, debounce, and local storage.', stars: 31, lang: 'JavaScript' },
        ],
      },
      contact: {
        title: 'Get in Touch',
        subtitle: "Have a project in mind? Let's build something amazing together.",
        nameLabel: 'Full Name',
        emailLabel: 'Email Address',
        messageLabel: 'Message',
        namePlaceholder: 'Your name',
        emailPlaceholder: 'your@email.com',
        messagePlaceholder: 'Tell me about your project...',
        send: 'Send Message',
        sending: 'Sending...',
        success: "Message sent! I'll get back to you soon.",
        error: 'Something went wrong. Please try again.',
        detailsTitle: 'Contact Details',
        email: 'faridunabdurazakov0@gmail.com',
        location: 'Tashkent, Uzbekistan',
        availability: 'Available for work',
        telegram: 'Telegram',
        instagram: 'Instagram',
        emailLabel2: 'Email',
        locationLabel2: 'Location',
        availableStatus: 'Available for Frontend Projects',
        availableDesc: 'I typically respond within 24 hours. Open to freelance work, collaborations, and creative projects.',
        quickResponse: 'Quick Response',
        locationTitle: 'Location & Timezone',
        cityLabel: 'City',
        countryLabel: 'Country',
        timezoneLabel: 'Timezone',
        cityValue: 'Tashkent',
        countryValue: 'Uzbekistan',
        timezoneValue: 'UTC+5',
        faqTitle: 'Frequently Asked Questions',
        faqSubtitle: 'Quick answers to common questions about working with me',
        faq: [
          { q: 'What technologies do you specialize in?', a: 'I specialize in frontend development with React.js, Tailwind CSS, JavaScript ES6+, HTML5, and CSS3. I also use Framer Motion for animations, Firebase for backend integration, and Vite for fast builds.' },
          { q: 'Are you available for freelance projects?', a: "Yes! I'm currently available for frontend freelance projects, UI/UX implementation, and React-based web applications. Feel free to reach out through the contact form or my social channels." },
          { q: 'How long does a typical project take?', a: 'Project timelines vary based on complexity. A simple landing page can take 1-2 weeks, while a full React application with multiple pages and features typically takes 3-6 weeks. I always provide detailed estimates before starting.' },
          { q: 'Do you work with existing codebases?', a: 'Absolutely! I can integrate into existing projects, refactor components, improve responsive design, add animations, or build new features on top of your current stack.' },
          { q: 'What is your development process?', a: 'I follow a structured workflow: 1) Understand requirements and plan component structure, 2) Build with React + Tailwind, 3) Add animations and interactions, 4) Test responsiveness across devices, 5) Optimize and deploy.' },
          { q: 'Can you work with backend developers?', a: 'Yes, I work well in team environments. I handle the frontend layer \u2014 components, styling, state management, and API integration \u2014 while collaborating with backend developers on data flow and endpoints.' },
        ],
      },
      services: {
        title: 'Services',
        subtitle: 'What I can do for your next project',
        s1Title: 'Modern Web Layouts',
        s1Desc: 'Beautiful, semantic HTML structures with modern CSS \u2014 Flexbox, Grid, custom properties, and responsive breakpoints that adapt to any screen.',
        s2Title: 'Responsive UI Design',
        s2Desc: 'Mobile-first interfaces built with Tailwind CSS and React. Every component is tested across devices to ensure a native, fluid experience.',
        s3Title: 'Performance & Animation',
        s3Desc: 'Smooth 60fps animations with Framer Motion, optimized rendering, lazy loading, and clean component architecture for blazing-fast apps.',
      },
      footer: { copyright: 'All rights reserved.', builtWith: 'Crafted with care by Faridun Abdurazakov' },
    },
  },

  uz: {
    translation: {
      nav: { home: 'Bosh sahifa', about: 'Men haqimda', skills: "Ko'nikmalar", projects: 'Loyihalar', contact: 'Aloqa' },
      home: {
        greeting: 'Salom, men',
        name: 'Faridun Abdurazakov',
        title: 'Frontend Veb Dasturchi',
        description: 'React va toza CSS bilan zamonaviy, responsive veb-interfeyslar yarataman. Pixelga mos UI/UX dizayn va silliq animatsiyalarga ishqibozman.',
        hireMe: 'Meni yollang',
        exploreWork: 'Ishlarimni ko\'ring',
        profileAlt: 'Ish uchun mavjud',
        stat1Value: '1+', stat1Label: 'Yillik tajriba',
        stat2Value: '10+', stat2Label: 'Yaratilgan loyihalar',
        stat3Value: '100%', stat3Label: 'Fidoyilik',
        bioTitle: 'Men kimman',
        bioText: "Men Faridun Abdurazakov \u2014 O'zbekistonda yashovchi, 1 yillik amaliy tajribaga ega Frontend Veb Dasturchiman. React, HTML5, CSS3 va Tailwind CSS bilan chiroyli, responsive interfeyslar qurishga ixtisoslashganman.",
        roles: ['Frontend Dasturchi', 'React Ishqiboz', 'UI/UX Dizayner', 'CSS Ustasi'],
        philosophy: ['Pixelga mos UI/UX dizayn', 'Toza, saqlash mumkin kod', 'Mobile-first yondashuv'],
        numbersTitle: 'Raqamlarda',
        numbersSubtitle: 'Frontend sayohatimning hozirgi holati',
        metrics: [
          { value: '10+', label: 'Yaratilgan loyihalar', desc: 'Landing sahifalardan to\'liq React ilovalargacha' },
          { value: '7+', label: 'Texnologiyalar', desc: 'React, JS, HTML, CSS, Tailwind, Git, Firebase' },
          { value: '500+', label: 'Kod soatlari', desc: "Amaliy mashq va haqiqiy loyihalar" },
          { value: '100%', label: 'Fidoyilik', desc: "Har bir piksel e'tibor bilan yaratilgan" },
        ],
        featuredTitle: 'Tanlangan ishlar',
        featuredSubtitle: 'Eng so\'nggi loyihalarimning oldindan ko\'rish',
        viewAll: 'Barcha loyihalarni ko\'rish',
        capabilitiesTitle: 'Nima qila olaman',
        capabilitiesSubtitle: 'Har bir loyihada keltiradigan asosiy frontend qobiliyatlarim',
        capabilities: [
          { title: 'Zamonaviy Veb Tartiblari', desc: 'Flexbox, Grid va CSS xususiyatlari bilan semantik HTML5 tuzilmalari.' },
          { title: 'Responsive UI Dizayn', desc: 'Tailwind CSS komponentlari telefon, planshet va kompyuterlarda sinovdan o\'tkazilgan.' },
          { title: 'Animatsiya Qo\'shish', desc: 'Framer Motion o\'tishlari, CSS keyframes va micro-interactions.' },
        ],
        workflowTitle: 'Mening Ish Jarayonim',
        workflowSubtitle: "G'oyadan deploy qilinadigan ilovagacha",
        workflow: [
          { step: '01', title: 'Rejalashtirish', desc: 'Komponent tuzilmasi & props' },
          { step: '02', title: 'Qurish', desc: 'React + Tailwind yig\'ish' },
          { step: '03', title: 'Animatsiya', desc: 'Framer Motion o\'tishlari' },
          { step: '04', title: 'Tekshirish', desc: 'Cross-device responsive' },
          { step: '05', title: 'Chiqarish', desc: 'Optimallashtirish & deploy' },
        ],
        ctaTitle: "Keling, birga narsa yaratamiz",
        ctaText: "Yangi loyihalar, ijodiy g'oyalar yoki sizning viziyangizning bir qismi bo'lish imkoniyatlari haqida doimo ochiqman. Menga xabar yuboring va suhbatni boshlaylik.",
        ctaPrimary: "Bog'lanish",
        ctaSecondary: 'Telegram orqali xabar',
        featuredProjects: [
          { name: 'Portfolio v2', tags: ['React', 'Tailwind', 'Framer Motion'] },
          { name: 'Ob-havo Paneli', tags: ['React', 'Chart.js', 'API'] },
          { name: 'Vazifalar Ilovasi', tags: ['React', 'DnD', 'LocalStorage'] },
        ],
      },
      about: {
        title: 'Men haqimda',
        subtitle: "Mening yo'lim, filosofiyam va frontendga bo'lgan ishqibozligim",
        bioTitle: "Mening hikoyam",
        bioText1: "Men Faridun Abdurazakov \u2014 1 yillik tajribaga ega Frontend Veb Dasturchiman. Sayohatim chiroyli veb-saytlar qanday qurilishiga qiziqish bilan boshlangan va tezda React, responsive dizayn va pixelga mos UI yaratishga chuqur ishqibozlikka aylangan.",
        bioText2: "Filosofiyam toza, saqlash mumkin bo'lgan kod yozish va har qarorda foydalanuvchini markazga qo'yishga asoslangan. Ajoyib frontend ishi tafsilotlarda \u2014 silliq o'tishlar, qulay tartiblar va intuitiv interfeyslar.",
        bioText3: "Har kuni yangi narsa o'rganaman \u2014 zamonaviy CSS texnikalari, React naqshlari va kutubxonalarni o'rganib boraman.",
        timelineTitle: "Mening yo'lim",
        timelineSubtitle: "Birinchi HTML tegimdan zamonaviy React ilovagacha",
        timeline: [
          { period: `${currentYear} \u2014 Hozir`, role: 'Frontend Veb Dasturchi', company: 'Mustaqil / Freelance', desc: 'React, Tailwind CSS va Framer Motion bilan zamonaviy veb-interfeyslar quraman. Responsive UI/UX dizayn, komponent arxitekturasi va samaradorlikni optimallashtirishga e\'tibor qarataman.' },
          { period: `2023 \u2014 ${currentYear}`, role: "Frontend O'rganuvchi", company: "O'z-o'zini o'rgatish", desc: "HTML5, CSS3, JavaScript va React bo'yicha chuqur o'rganish. Responsive dizayn va zamonaviy frontend naqshlarini master qilish uchun shaxsiy loyihalar yaratdim." },
          { period: '2023', role: "Dasturlash yo'lini boshladim", company: 'Birinchi qadamlar', desc: "Birinchi HTML va CSS satrlarini yozdim. Oddiy statik sahifalar qurdim va dizaynlarni haqiqiy veb-sahifalarga aylantirishga ishqibozlikni kashf etdim." },
        ],
        statsTitle: 'Raqamlarda',
        stat1: { value: '1+', label: 'Yillik tajriba' },
        stat2: { value: '10+', label: 'Tugallangan loyihalar' },
        stat3: { value: '7+', label: 'Texnologiyalar' },
        stat4: { value: '100%', label: 'Fidoyilik' },
        principlesTitle: 'Dasturlash tamoyillari',
        principlesSubtitle: "Har bir loyihani boshqaradigan qadriyatlar",
        principles: [
          { title: 'Pixelga mos UI', desc: "Har bir element o'lchangan, tekislangan va silliqlashtirilgan. Joylashuv, tipografiya va vizual ierarxiyaga qiziqaman." },
          { title: 'Toza Kod', desc: "O'qiladigan, saqlanadigan va tuzilgan komponentlar. Boshqa dasturchilar tushuna oladigan kod yozaman." },
          { title: 'Mobile First', desc: "Har bir interfeys eng kichik ekrandan boshlanadi va kattalashadi. Bu telefon, planshet yoki kompyuterda silliq tajribani ta'minlaydi." },
        ],
        toolsTitle: "Ishonchim vositalari",
        toolsSubtitle: "Kunlik ish jarayonimni quvvatlantiradigan texnologiyalar",
        tools: [
          { name: 'React.js', icon: '\u269B\uFE0F', desc: "Interaktiv interfeyslar qurish uchun komponentga asoslangan kutubxona" },
          { name: 'Tailwind CSS', icon: '\uD83C\uDFA8', desc: "Tez va bir xil uslub uchun utility-first CSS framework" },
          { name: 'Git & GitHub', icon: '\uD83D\uDD27', desc: "Versiyalarni boshqarish va jamoaviy kod" },
          { name: 'Vite', icon: '\u26A1', desc: "Darhol HMR bilan keyingi avlod build vositasi" },
          { name: 'Firebase', icon: '\uD83D\uDD25', desc: "Autentifikatsiya va Firestore ma'lumotlar bazasi uchun BaaS" },
          { name: 'VS Code', icon: '\uD83D\uDCBB', desc: "Optimallashtirilgan kengaytmalar bilan asosiy kod muharriri" },
        ],
        interestsTitle: 'Kod tashqarida',
        interestsSubtitle: "Dasturlashdan tashqarida meni ilhomlantiradigan narsalar",
        interests: [
          { title: 'UI Dizayn Ilhom', desc: "Dribbble, Behance va Apple dizayn tizimini o'rganib, yangi g'oyalar topaman." },
          { title: 'Texnologiya Trendlari', desc: "React Server Components, CSS container queries va JavaScript ekotizimini kuzataman." },
          { title: "Doimiy o'rganish", desc: "Har kuni yangi narsa o'rganish imkoniyati \u2014 CSS hiyli, React naqhi yoki dizayn tamoyili bo'lsin." },
        ],
        valuesTitle: "Mening qadriyatlarim",
        valuesSubtitle: "Har bir loyihaga yondashuvimni aniqlaydigan tamoyillar",
        values: [
          { title: 'Sifat miqdordan ustun', desc: "Bir ajoyib loyiha qurganimni o'n oddiy loyihadan ko'ra afzal bilaman. Har bir kod satriga to'liq e'tibor beraman." },
          { title: "Doimiy o'rganish", desc: "Veb tez o'zgaradi. Hujjatlar o'qib, videolar ko'rib, loyihalar qurib bilimlarimni yangilab turaman." },
          { title: 'Tafsilotlarga e\'tibor', desc: "Yaxshi va ajoyib o'rtasidagi farq tafsilotlarda \u2014 silliq o'tishlar, mukammal joylashuv va intuitiv foydalanuvchi oqimi." },
        ],
        ctaTitle: "Bog'lanmoqchimisiz?",
        ctaText: "Frontend dasturlash, yangi loyihalar yoki oddiy salom haqida suhbatlashishdan doimo xursandman.",
        ctaButton: 'Xabar yuborish',
      },
      skills: {
        title: "Ko'nikmalarim va Tech Stack",
        subtitle: "G'oyalarni hayotga tatbiq etish uchun ishlatadigan frontend texnologiyalari",
        frontend: 'Frontend Dasturlash',
        tools: 'Vositalar & Ish jarayoni',
        skillDetails: [
          { title: 'React.js ustasi', level: 80, topics: ['Funksional komponentlar & Hooks', 'useState, useEffect, useContext', 'React Router navigatsiya', 'Framer Motion animatsiyalar', 'Komponent tuzish naqshlari', 'Props drilling & state lifting'] },
          { title: 'Tailwind CSS & Stil', level: 88, topics: ['Utility-first CSS', "Responsive dizayn (mobile-first)", 'Flexbox & CSS Grid', 'CSS o\'zgaruvchilar bilan theming', 'Dark mode', 'Glassmorphism & backdrop'] },
          { title: 'JavaScript ES6+', level: 75, topics: ['Arrow funksiyalar & destructuring', 'Template literals & spread', 'Promises & async/await', 'Array metodlari (map, filter, reduce)', 'Modullar (import/export)', 'DOM manipulyatsiya'] },
          { title: 'HTML5 & CSS3 Standartlari', level: 90, topics: ['Semantik HTML elementlar', 'CSS animatsiyalar & o\'tishlar', 'CSS xususiyatlari', 'Forma tasdiqlash & qulaylik', 'Media queries & breakpointlar', 'CSS transforms & keyframes'] },
        ],
        devToolsTitle: 'Dasturlash vositalari',
        devToolsSubtitle: "Kunlik dasturlash ish jarayonimni quvvatlantiradigan vositalar",
        devTools: [
          { name: 'VS Code', icon: '\uD83D\uDCBB', desc: 'Prettier, ESLint, Tailwind IntelliSense va GitLens kengaytmalari bilan asosiy muharrir.', level: 'Power User' },
          { name: 'Git & GitHub', icon: '\uD83D\uDD27', desc: 'Branch strategiyalari, pull requestlar va jamoaviy ish jarayoni bilan versiya boshqaruvi.', level: 'Kunlik' },
          { name: 'Vite', icon: '\u26A1', desc: 'Tez rivojlantirish uchun darhol HMR bilan tezkor build vositasi.', level: 'Build' },
          { name: 'npm', icon: '\uD83D\uDCE6', desc: 'Paket boshqaruvi, skript avtomatlashtirish va bog\'liqliklar.', level: 'Zaruriy' },
          { name: 'Chrome DevTools', icon: '\uD83D\uDD0D', desc: 'Samaradorlik profilini tuzish, responsive tuzatish va tarmoq tahlili.', level: 'Tuzatish' },
          { name: 'Figma', icon: '\uD83C\uDFA8', desc: 'Dizayndan koda, aktivlarni tekshirish va dizayn tavsiflarini tushunish.', level: 'Dizayn' },
        ],
        firebaseTitle: 'Firebase Integratsiyasi',
        firebaseSubtitle: "Silliq ma'lumotlar boshqaruvi uchun BaaS",
        firebaseSubheading: 'Firebase Firestore',
        firebaseFeatures: [
          { title: "Firestore Ma'lumotlar bazasi", desc: "Aloqa formasi yuborishlari, foydalanuvchi ma'lumotlari va ilova holatini real vaqtda saqlash uchun hujjatga asoslangan NoSQL baza." },
          { title: "Aloqa Formasi Integratsiyasi", desc: "Forma yuborishlari bevosita Firestore xabarlar kolleksiyasiga vaqt belgilari bilan saqlanadi." },
          { title: "Real vaqt yangilanishlari", desc: "Firestore real vaqt sinxronizatsiyasini ta'minlaydi, ulangan mijozlarda darhol ma'lumot aks etadi." },
        ],
        uiuxTitle: 'UI/UX Dizayn Amaliyotlari',
        uiuxSubtitle: "Vizual dizayn va foydalanuvchi tajribasiga qanday yondashaman",
        uiux: [
          { title: 'Framedan Kodga', desc: "Dizayn namunalarini pixelga mos React komponentlariga aylantirish." },
          { title: 'Glassmorphism Dizayn', desc: "Backdrop-blur, yarim-shaffof fon va yumshoq chegaralar bilan sovuq shisha effektlari." },
          { title: 'Responsive Mobil', desc: "Tailwind responsive vositalari bilan telefon, planshet va kompyuterlarda optimal layoutlar." },
          { title: 'Micro-Interactions', desc: "Hover effektlari, yuklanish holatlari va o'tish animatsiyalari qo'shish." },
        ],
        roadmapTitle: "O'rganish yo'nalishi",
        roadmapSubtitle: "Hozir o'rganayotgan va rejalashtirgan texnologiyalarim",
        roadmap: [
          { tech: 'TypeScript', status: "O'rganilmoqda", desc: 'React loyihalariga tip xavfsizligi qo\'shish.' },
          { tech: 'Next.js', status: 'O\'rganilmoqda', desc: 'Server-side rendering, statik generatsiya va to\'liq React framework.' },
          { tech: 'React Native', status: 'Rejalashtirilgan', desc: "Tanish React naqshlari bilan mobil ilovalar qurish." },
          { tech: 'Testing (Jest)', status: 'Rejalashtirilgan', desc: 'Ishonchli frontend kodlari uchun unit va integratsiya testlari.' },
        ],
      },
      projects: {
        title: 'Loyihalar',
        subtitle: 'Frontend ishlarim va tajribalarim tanlanmasi',
        viewDemo: 'Demo',
        viewRepo: 'Manba kodi',
        featured: 'Tanlangan',
        all: 'Hammasi',
        filter1: 'Veb ilovalar',
        filter2: 'Mobil',
        filter3: 'Ochiq manba',
        project1: { name: 'Portfolio v2', category: 'web', description: "React, Tailwind CSS va Framer Motion bilan yaratilgan shaxsiy portfolio. iOS glassmorphism dizayni, dark mode va ko'p tilli qo'llab-quvvatlash.", tags: ['React', 'Tailwind', 'Framer Motion'] },
        project2: { name: 'Ob-havo Paneli', category: 'web', description: "7 kunlik prognozlar, interaktiv xaritalar va chiroyli vizualizatsiyalar bilan responsive ob-havo paneli.", tags: ['React', 'Chart.js', 'API'] },
        project3: { name: 'Vazifalar Ilovasi', category: 'web', description: "Drag-and-drop, kategoriyalar va local storage bilan minimal vazifa boshqaruv ilovasi.", tags: ['React', 'DnD', 'LocalStorage'] },
        project4: { name: 'E-Commerce UI', category: 'web', description: "Mahsulot kartochkalari, savat va chiroyli to'lov jarayoni bilan responsive e-commerce landing sahifasi.", tags: ['React', 'CSS3', 'Responsive'] },
        project5: { name: 'Chat Ilova UI', category: 'mobile', description: "Xabar pufakchalari, indicatorlar va silliq o'tishlar bilan mobile-first chat interfeysi.", tags: ['React', 'Mobile UI', 'Animations'] },
        project6: { name: 'CSS Sanat Galereyasi', category: 'opensource', description: "Faqat CSS yordamida yaratilgan ijodiy sanat asarlari va animatsiyalar to'plami.", tags: ['CSS3', 'Animations', 'Open Source'] },
        caseStudyTitle: 'Loyiha tahlili',
        caseStudySubtitle: 'Arxitekturasi haqida chuqur nazar',
        caseStudy: {
          name: 'Portfolio v2',
          stack: ['React', 'Tailwind CSS', 'Framer Motion', 'Firebase', 'i18next'],
          features: ['iOS glassmorphism dizayn tizimi', 'Dark/Light mode saqlanishi', "3 tilli qo'llab-quvvatlash (EN/UZ/RU)", 'Firebase Firestore aloqa formasi', "Animatsiyali sahifalar o'tishi", "To'liq responsive mobil-first layout"],
          architecture: "React Router bilan ko'p sahifali navigatsiya uchun React ilovasi sifatida qurilgan. Komponentlar /components (qayta ishlatiladigan UI), /pages (marshaurlar) va /context (tema va til boshqaruvi) ichida tashkil etilgan.",
        },
        openSourceTitle: 'Ochiq manba',
        openSourceSubtitle: "Hissalar va jamoaviy loyihalar",
        openSource: [
          { name: 'CSS Sanat Galereyasi', desc: "Ijodiy faqat CSS sanat asarlari va animatsiyalar.", stars: 24, lang: 'CSS' },
          { name: 'Tailwind Glass Utils', desc: "Tailwind CSS loyihalari uchun qayta ishlatiladigan glassmorphism utility sinflari.", stars: 18, lang: 'CSS' },
          { name: 'React Hook Snippets', desc: "Forma boshqaruvi, debounce va local storage uchun umumiy hooklar.", stars: 31, lang: 'JavaScript' },
        ],
      },
      contact: {
        title: "Bog'laning",
        subtitle: "Loyihangiz bormi? Keling, birga ajoyib narsa yaratamiz.",
        nameLabel: "To'liq ism",
        emailLabel: 'Email manzil',
        messageLabel: 'Xabar',
        namePlaceholder: 'Ismingiz',
        emailPlaceholder: 'email@misol.com',
        messagePlaceholder: 'Loyihangiz haqida gapiring...',
        send: 'Xabar yuborish',
        sending: 'Yuborilmoqda...',
        success: 'Xabar yuborildi! Tez orada javob beraman.',
        error: "Xatolik yuz berdi. Qayta urinib ko'ring.",
        detailsTitle: "Aloqa ma'lumotlari",
        email: 'faridunabdurazakov0@gmail.com',
        location: "Toshkent, O'zbekiston",
        availability: 'Ish uchun mavjud',
        telegram: 'Telegram',
        instagram: 'Instagram',
        emailLabel2: 'Email',
        locationLabel2: 'Joylashuv',
        availableStatus: 'Frontend loyihalari uchun mavjud',
        availableDesc: "Odatda 24 soat ichida javob beraman. Freelance ish, hamkorlik va ijodiy loyihalar uchun ochiqman.",
        quickResponse: 'Tezkor javob',
        locationTitle: 'Joylashuv & Vaqt zonasi',
        cityLabel: 'Shahar',
        countryLabel: 'Mamlakat',
        timezoneLabel: 'Vaqt zona',
        cityValue: 'Toshkent',
        countryValue: "O'zbekiston",
        timezoneValue: 'UTC+5',
        faqTitle: "Ko'p beriladigan savollar",
        faqSubtitle: "Menga ishlash haqida tez-tez beriladigan savollarga javoblar",
        faq: [
          { q: "Qaysi texnologiyalarga ixtisoslashgansiz?", a: "Frontend dasturlash bo'yicha React.js, Tailwind CSS, JavaScript ES6+, HTML5 va CSS3 ga ixtisoslashganman. Shuningdek, Framer Motion animatsiyalar, Firebase backend integratsiyasi va Vite tezkor buildlari." },
          { q: "Freelance loyihalar uchun mavjudmisiz?", a: "Ha! Hozir frontend freelance loyihalar, UI/UX amalga oshirish va React asosidagi veb-ilovalar uchun mavjudman. Aloqa shakli yoki ijtimoiy tarmoqlarim orqali murojaat qiling." },
          { q: "Odatda loyiha qancha vaqt oladi?", a: "Loyiha muddatlari murakkablikka qarab o'zgaradi. Oddiy landing sahifa 1-2 hafta, to'liq React ilovasi 3-6 hafta vaqt oladi. Boshlashdan oldin batafsil hisob beraman." },
          { q: "Mavjud kod bazalari bilan ishlay olasizmi?", a: "Albatta! Mavjud loyihalarga qo'shilishim, komponentlarni qayta yozishim, responsive dizaynni yaxshilashim, animatsiyalar qo'shishim yoki joriy stack ustida yangi funksiyalar qurishim mumkin." },
          { q: "Dasturlash jaroyoniz qanday?", a: "Tizimli ish jaroyoniga amal qilaman: 1) Talablarni tushunish va komponent tuzilmasini rejalashtirish, 2) React + Tailwind bilan qurish, 3) Animatsiyalar qo'shish, 4) Responsive tekshirish, 5) Optimallashtirish va deploy." },
          { q: "Backend dasturchilar bilan ishlay olasizmi?", a: "Ha, jamoaviy muhitda yaxshi ishlayman. Frontend qatlamini \u2014 komponentlar, stillar, state boshqaruvi va API integratsiyasini \u2014 backend dasturchilar bilan hamkorlikda boshqaraman." },
        ],
      },
      services: {
        title: 'Xizmatlar',
        subtitle: 'Keyingi loyihangiz uchun nima qila olaman',
        s1Title: 'Zamonaviy Veb Tartiblari',
        s1Desc: "Flexbox, Grid, custom properties va responsive breakpointlar bilan chiroyli, semantik HTML tuzilmalari.",
        s2Title: 'Responsive UI Dizayn',
        s2Desc: "Tailwind CSS va React bilan qurilgan mobile-first interfeyslar. Har bir komponent barcha qurilmalarda sinovdan o'tkazilgan.",
        s3Title: 'Samaradorlik & Animatsiya',
        s3Desc: "Framer Motion bilan silliq 60fps animatsiyalar, optimallashtirilgan rendering va toza komponent arxitekturasi.",
      },
      footer: { copyright: 'Barcha huquqlar himoyalangan.', builtWith: 'Faridun Abdurazakov tomonidan sevgi bilan yaratilgan' },
    },
  },

  ru: {
    translation: {
      nav: { home: 'Главная', about: 'Обо мне', skills: 'Навыки', projects: 'Проекты', contact: 'Контакты' },
      home: {
        greeting: 'Привет, я',
        name: 'Фаридун Абдуразаков',
        title: 'Frontend Разработчик',
        description: 'Я создаю современные, адаптивные веб-интерфейсы на React и чистом CSS. Увлечён идеально точным UI/UX дизайном и плавными анимациями.',
        hireMe: 'Нанять меня',
        exploreWork: 'Посмотреть работы',
        profileAlt: 'Доступен для работы',
        stat1Value: '1+', stat1Label: 'Год опыта',
        stat2Value: '10+', stat2Label: 'Созданных проектов',
        stat3Value: '100%', stat3Label: 'Отдача',
        bioTitle: 'Кто я',
        bioText: 'Я Фаридун Абдуразаков \u2014 Frontend разработчик из Узбекистана с 1 годом практического опыта. Специализируюсь на создании красивых, адаптивных пользовательских интерфейсов с React, HTML5, CSS3 и Tailwind CSS.',
        roles: ['Frontend Разработчик', 'React Энтузиаст', 'UI/UX Дизайнер', 'CSS Мастер'],
        philosophy: ['Идеально точный UI/UX', 'Чистый, поддерживаемый код', 'Mobile-first подход'],
        numbersTitle: 'В цифрах',
        numbersSubtitle: 'Обзор моего frontend пути на данный момент',
        metrics: [
          { value: '10+', label: 'Созданных проектов', desc: 'От лендингов до полноценных React-приложений' },
          { value: '7+', label: 'Технологий', desc: 'React, JS, HTML, CSS, Tailwind, Git, Firebase' },
          { value: '500+', label: 'Часов кода', desc: 'Практика и реальные проекты' },
          { value: '100%', label: 'Отдача', desc: 'Каждый пиксель создан с вниманием' },
        ],
        featuredTitle: 'Избранные работы',
        featuredSubtitle: 'Обзор моих последних проектов',
        viewAll: 'Посмотреть все проекты',
        capabilitiesTitle: 'Что я делаю',
        capabilitiesSubtitle: 'Ключевые frontend компетенции, которые я привношу в каждый проект',
        capabilities: [
          { title: 'Современные веб-макеты', desc: 'Семантический HTML5 с Flexbox, Grid и CSS-переменными для идеальных структур.' },
          { title: 'Адаптивный UI-дизайн', desc: 'Mobile-first компоненты Tailwind CSS, проверенные на всех устройствах.' },
          { title: 'Анимации', desc: 'Переходы Framer Motion, CSS keyframes и микро-взаимодействия.' },
        ],
        workflowTitle: 'Мой рабочий процесс',
        workflowSubtitle: 'От идеи до развёрнутого приложения',
        workflow: [
          { step: '01', title: 'План', desc: 'Структура компонентов и пропсы' },
          { step: '02', title: 'Сборка', desc: 'React + Tailwind конструирование' },
          { step: '03', title: 'Анимация', desc: 'Переходы Framer Motion' },
          { step: '04', title: 'Тест', desc: 'Адаптивность на всех устройствах' },
          { step: '05', title: 'Деплой', desc: 'Оптимизация и развёртывание' },
        ],
        ctaTitle: 'Давайте создадим что-то вместе',
        ctaText: 'Я всегда открыт к обсуждению новых проектов, креативных идей или возможностей стать частью вашего видения. Напишите мне, и начнём разговор.',
        ctaPrimary: 'Связаться',
        ctaSecondary: 'Написать в Telegram',
        featuredProjects: [
          { name: 'Portfolio v2', tags: ['React', 'Tailwind', 'Framer Motion'] },
          { name: 'Погодная панель', tags: ['React', 'Chart.js', 'API'] },
          { name: 'Менеджер задач', tags: ['React', 'DnD', 'LocalStorage'] },
        ],
      },
      about: {
        title: 'Обо мне',
        subtitle: 'Мой путь, философия и страсть к фронтенду',
        bioTitle: 'Моя история',
        bioText1: 'Я Фаридун Абдуразаков \u2014 Frontend разработчик с 1 годом опыта создания современных веб-интерфейсов. Мой путь начался с любопытства о том, как создаются красивые сайты, и быстро превратился в страсть к React, адаптивному дизайну и созданию идеальных интерфейсов.',
        bioText2: 'Моя философия \u2014 писать чистый, поддерживаемый код, ставя пользователя в центр каждого решения. Отличный фронтенд \u2014 это детали: плавные переходы, удобные компоновки и интуитивные интерфейсы.',
        bioText3: 'Каждый день учусь чему-то новому \u2014 современным CSS-техникам, паттернам React и библиотекам анимаций.',
        timelineTitle: 'Мой путь',
        timelineSubtitle: 'От первого HTML-тега до современных React-приложений',
        timeline: [
          { period: `${currentYear} \u2014 Настоящее`, role: 'Frontend Разработчик', company: 'Фриланс / Самостоятельно', desc: 'Создаю современные веб-интерфейсы на React, Tailwind CSS и Framer Motion. Фокус на адаптивном UI/UX, архитектуре компонентов и оптимизации производительности.' },
          { period: `2023 \u2014 ${currentYear}`, role: 'Изучаю Frontend', company: 'Самообразование', desc: 'Изучил HTML5, CSS3, JavaScript и React. Создавал личные проекты для освоения адаптивного дизайна и современных фронтенд-паттернов.' },
          { period: '2023', role: 'Начал путь в коде', company: 'Первые шаги', desc: 'Написал первые строки HTML и CSS. Создавал простые статические страницы и обнаружил страсть к превращению дизайнов в реальные интерактивные веб-страницы.' },
        ],
        statsTitle: 'В цифрах',
        stat1: { value: '1+', label: 'Год опыта' },
        stat2: { value: '10+', label: 'Завершённых проектов' },
        stat3: { value: '7+', label: 'Используемых технологий' },
        stat4: { value: '100%', label: 'Отдача' },
        principlesTitle: 'Принципы разработки',
        principlesSubtitle: 'Ценности, которые направляют каждый мой проект',
        principles: [
          { title: 'Идеально точный UI', desc: 'Каждый элемент измерен, выровнен и отполирован. Уделяю внимание пространству, типографике и визуальной иерархии.' },
          { title: 'Чистый код', desc: 'Читаемые, поддерживаемые и структурированные компоненты. Пишу код, который другие разработчики могут понять и расширить.' },
          { title: 'Mobile First', desc: 'Каждый интерфейс начинается с наименьшего экрана и масштабируется вверх. Это обеспечивает нативный опыт на любом устройстве.' },
        ],
        toolsTitle: 'Мои инструменты',
        toolsSubtitle: 'Технологии, которые обеспечивают мой ежедневный рабочий процесс',
        tools: [
          { name: 'React.js', icon: '\u269B\uFE0F', desc: 'Компонентная UI-библиотека для создания интерактивных интерфейсов' },
          { name: 'Tailwind CSS', icon: '\uD83C\uDFA8', desc: 'Utility-first CSS фреймворк для быстрого и一致ного стиля' },
          { name: 'Git & GitHub', icon: '\uD83D\uDD27', desc: 'Контроль версий и совместное управление кодом' },
          { name: 'Vite', icon: '\u26A1', desc: 'Сборщик нового поколения с мгновенным HMR' },
          { name: 'Firebase', icon: '\uD83D\uDD25', desc: 'BaaS для аутентификации и базы данных Firestore' },
          { name: 'VS Code', icon: '\uD83D\uDCBB', desc: 'Основной редактор кода с оптимизированными расширениями' },
        ],
        interestsTitle: 'За пределами кода',
        interestsSubtitle: 'Что вдохновляет и мотивирует меня вне разработки',
        interests: [
          { title: 'Вдохновение UI-дизайна', desc: "Исследую Dribbble, Behance и дизайн-систему Apple для свежих идей интерфейсов и паттернов взаимодействий." },
          { title: 'Технологические тренды', desc: 'Слежу за последними тенденциями в React Server Components, CSS container queries и экосистеме JavaScript.' },
          { title: 'Непрерывное обучение', desc: 'Каждый день \u2014 возможность узнать что-то новое: CSS-трюк, паттерн React или принцип дизайна.' },
        ],
        valuesTitle: 'Мои ценности',
        valuesSubtitle: 'Принципы, определяющие мой подход к каждому проекту',
        values: [
          { title: 'Качество важнее количества', desc: 'Я лучше создам один выдающийся проект, чем десять посредственных. Каждая строка кода получает моё полное внимание.' },
          { title: 'Непрерывное обучение', desc: 'Веб развивается быстро. Я читаю документацию, смотрю туториалы и создаю side-проекты, чтобы расти.' },
          { title: 'Внимание к деталям', desc: 'Разница между хорошим и великим \u2014 в деталях: плавные переходы, идеальное пространство и интуитивные пользовательские потоки.' },
        ],
        ctaTitle: 'Хотите связаться?',
        ctaText: 'Я всегда рад обсудить frontend-разработку, новые проекты или просто поздороваться.',
        ctaButton: 'Написать сообщение',
      },
      skills: {
        title: 'Навыки и стек',
        subtitle: 'Frontend-технологии, которые я использую для воплощения идей',
        frontend: 'Frontend Разработка',
        tools: 'Инструменты и рабочий процесс',
        skillDetails: [
          { title: 'React.js', level: 80, topics: ['Функциональные компоненты и Hooks', 'useState, useEffect, useContext', 'React Router для навигации', 'Анимации Framer Motion', 'Паттерны композиции компонентов', 'Props drilling и state lifting'] },
          { title: 'Tailwind CSS и стилизация', level: 88, topics: ['Utility-first CSS', 'Адаптивный дизайн (mobile-first)', 'Flexbox и CSS Grid', 'Темы с CSS-переменными', 'Тёмная тема', 'Glassmorphism и backdrop'] },
          { title: 'JavaScript ES6+', level: 75, topics: ['Стрелочные функции и деструктуризация', 'Шаблонные строки и spread-оператор', 'Промисы и async/await', 'Методы массивов (map, filter, reduce)', 'Модули (import/export)', 'Манипуляции с DOM'] },
          { title: 'HTML5 и CSS3', level: 90, topics: ['Семантические HTML-элементы', 'CSS-анимации и переходы', 'CSS-переменные', 'Валидация форм и доступность', 'Media queries', 'CSS-трансформации'] },
        ],
        devToolsTitle: 'Инструменты разработки',
        devToolsSubtitle: 'Инструменты, обеспечивающие мой ежедневный рабочий процесс',
        devTools: [
          { name: 'VS Code', icon: '\uD83D\uDCBB', desc: 'Основной редактор с Prettier, ESLint, Tailwind IntelliSense и GitLens.', level: 'Power User' },
          { name: 'Git & GitHub', icon: '\uD83D\uDD27', desc: 'Контроль версий с ветвлением, pull request и совместной работой.', level: 'Ежедневно' },
          { name: 'Vite', icon: '\u26A1', desc: 'Быстрый сборщик с мгновенным HMR.', level: 'Сборка' },
          { name: 'npm', icon: '\uD83D\uDCE6', desc: 'Управление пакетами, скриптами и зависимостями.', level: 'Необходимый' },
          { name: 'Chrome DevTools', icon: '\uD83D\uDD0D', desc: 'Профилирование, отладка адаптивности и анализ сети.', level: 'Отладка' },
          { name: 'Figma', icon: '\uD83C\uDFA8', desc: 'Workflow дизайна в код, проверка ресурсов.', level: 'Дизайн' },
        ],
        firebaseTitle: 'Интеграция Firebase',
        firebaseSubtitle: 'BaaS для бесперебойной работы с данными',
        firebaseSubheading: 'Firebase Firestore',
        firebaseFeatures: [
          { title: 'База данных Firestore', desc: 'Документальная NoSQL база для хранения данных форм, пользователей и состояния приложения в реальном времени.' },
          { title: 'Интеграция контактной формы', desc: 'Данные форм сохраняются в коллекцию messages Firestore с таймстампами для отслеживания.' },
          { title: 'Обновления в реальном времени', desc: 'Firestore обеспечивает синхронизацию в реальном времени для мгновенного отражения данных.' },
        ],
        uiuxTitle: 'Практики UI/UX дизайна',
        uiuxSubtitle: 'Как я подхожу к визуальному дизайну и пользовательскому опыту',
        uiux: [
          { title: 'Figma в код', desc: 'Преобразование макетов в идеально точные React-компоненты с точными отступами, типографикой и цветом.' },
          { title: 'Glassmorphism', desc: 'Создание эффектов матового стекла с backdrop-blur, полупрозрачными фонами и тонкими рамками.' },
          { title: 'Мобильная адаптивность', desc: 'Тестирование и оптимизация компоновки на всех устройствах с утилитами Tailwind.' },
          { title: 'Микро-взаимодействия', desc: 'Hover-эффекты, состояния загрузки и анимации переходов, оживляющие интерфейсы.' },
        ],
        roadmapTitle: 'Дорожная карта обучения',
        roadmapSubtitle: 'Технологии, которые я изучаю и планирую освоить',
        roadmap: [
          { tech: 'TypeScript', status: 'Изучается', desc: 'Добавление типизации в React-проекты для лучшего DX и меньшего числа ошибок.' },
          { tech: 'Next.js', status: 'Изучается', desc: 'SSR, статическая генерация и полноценный React-фреймворк для продакшена.' },
          { tech: 'React Native', status: 'Запланировано', desc: 'Создание нативных мобильных приложений с помощью привычных React-паттернов.' },
          { tech: 'Testing (Jest)', status: 'Запланировано', desc: 'Юнит- и интеграционное тестирование для надёжных фронтенд-проектов.' },
        ],
      },
      projects: {
        title: 'Проекты',
        subtitle: 'Подборка моих frontend-работ и экспериментов',
        viewDemo: 'Демо',
        viewRepo: 'Исходный код',
        featured: 'Избранное',
        all: 'Все',
        filter1: 'Веб-приложения',
        filter2: 'Мобильные',
        filter3: 'Open Source',
        project1: { name: 'Portfolio v2', category: 'web', description: 'Личное портфолио на React, Tailwind CSS и Framer Motion. iOS glassmorphism дизайн, dark mode и мультиязычность.', tags: ['React', 'Tailwind', 'Framer Motion'] },
        project2: { name: 'Погодная панель', category: 'web', description: 'Адаптивная погодная панель с прогнозами на 7 дней, интерактивными картами и визуализациями.', tags: ['React', 'Chart.js', 'API'] },
        project3: { name: 'Менеджер задач', category: 'web', description: 'Минимальное приложение для задач с drag-and-drop, категориями и хранением в localStorage.', tags: ['React', 'DnD', 'LocalStorage'] },
        project4: { name: 'E-Commerce UI', category: 'web', description: 'Адаптивная лендинг-страница e-commerce с карточками товаров, корзиной и оформлением заказа.', tags: ['React', 'CSS3', 'Responsive'] },
        project5: { name: 'Chat App UI', category: 'mobile', description: 'Mobile-first интерфейс чата с пузырями сообщений, индикаторами и плавными переходами.', tags: ['React', 'Mobile UI', 'Animations'] },
        project6: { name: 'CSS Art Gallery', category: 'opensource', description: 'Коллекция креативных произведений искусства и анимаций, созданных только на CSS.', tags: ['CSS3', 'Animations', 'Open Source'] },
        caseStudyTitle: 'Кейс-стади',
        caseStudySubtitle: 'Подробный анализ архитектуры',
        caseStudy: {
          name: 'Portfolio v2',
          stack: ['React', 'Tailwind CSS', 'Framer Motion', 'Firebase', 'i18next'],
          features: ['Дизайн-система iOS glassmorphism', 'Тёмная/светлая тема с сохранением', '3 языка (EN/UZ/RU)', 'Firebase Firestore контактная форма', 'Анимированные переходы страниц', 'Полностью адаптивный mobile-first layout'],
          architecture: 'Построено как одностраничное React-приложение с React Router для многостраничной навигации. Компоненты организованы в /components для переиспользуемого UI, /pages для маршрутов и /context для глобального управления состоянием.',
        },
        openSourceTitle: 'Open Source',
        openSourceSubtitle: 'Вклад и проекты сообщества',
        openSource: [
          { name: 'CSS Art Gallery', desc: 'Креативные произведения искусства и анимации только на CSS.', stars: 24, lang: 'CSS' },
          { name: 'Tailwind Glass Utils', desc: 'Переиспользуемые utility-классы glassmorphism для Tailwind CSS.', stars: 18, lang: 'CSS' },
          { name: 'React Hook Snippets', desc: 'Кастомные React-хуки для форм, debounce и localStorage.', stars: 31, lang: 'JavaScript' },
        ],
      },
      contact: {
        title: 'Свяжитесь со мной',
        subtitle: 'Есть проект? Давайте создадим что-то потрясающее вместе.',
        nameLabel: 'Полное имя',
        emailLabel: 'Email',
        messageLabel: 'Сообщение',
        namePlaceholder: 'Ваше имя',
        emailPlaceholder: 'ваш@email.com',
        messagePlaceholder: 'Расскажите о вашем проекте...',
        send: 'Отправить сообщение',
        sending: 'Отправка...',
        success: 'Сообщение отправлено! Скоро отвечу.',
        error: 'Что-то пошло не так. Попробуйте ещё раз.',
        detailsTitle: 'Контактные данные',
        email: 'faridunabdurazakov0@gmail.com',
        location: 'Ташкент, Узбекистан',
        availability: 'Доступен для работы',
        telegram: 'Telegram',
        instagram: 'Instagram',
        emailLabel2: 'Email',
        locationLabel2: 'Местоположение',
        availableStatus: 'Доступен для frontend-проектов',
        availableDesc: 'Обычно отвечаю в течение 24 часов. Открыт для фриланса, совместных проектов и креативных заданий.',
        quickResponse: 'Быстрый ответ',
        locationTitle: 'Местоположение и часовой пояс',
        cityLabel: 'Город',
        countryLabel: 'Страна',
        timezoneLabel: 'Часовой пояс',
        cityValue: 'Ташкент',
        countryValue: 'Узбекистан',
        timezoneValue: 'UTC+5',
        faqTitle: 'Часто задаваемые вопросы',
        faqSubtitle: 'Быстрые ответы на типичные вопросы о работе со мной',
        faq: [
          { q: 'В каких технологиях вы специализируетесь?', a: 'Я специализируюсь на frontend-разработке: React.js, Tailwind CSS, JavaScript ES6+, HTML5 и CSS3. Также использую Framer Motion для анимаций, Firebase для бэкенда и Vite для быстрой сборки.' },
          { q: 'Вы доступны для фриланс-проектов?', a: 'Да! Я открыт для фриланс-проектов, реализации UI/UX и React-приложений. Свяжитесь через форму или социальные сети.' },
          { q: 'Сколько времени занимает типичный проект?', a: 'Сроки зависят от сложности. Простой лендинг \u2014 1-2 недели, полноценное React-приложение \u2014 3-6 недель. Всегда предоставляю подробные оценки перед началом.' },
          { q: 'Вы работаете с существующими кодовыми базами?', a: 'Конечно! Могу интегрироваться в существующие проекты, рефакторить компоненты, улучшать адаптивность, добавлять анимации или строить новые функции на вашем стеке.' },
          { q: 'Какой у вас процесс разработки?', a: 'Структурированный подход: 1) Понимание требований и планирование, 2) Сборка на React + Tailwind, 3) Анимации и взаимодействия, 4) Тестирование адаптивности, 5) Оптимизация и деплой.' },
          { q: 'Можете ли вы работать с бэкенд-разработчиками?', a: 'Да, я хорошо работаю в команде. Я отвечаю за фронтенд \u2014 компоненты, стили, управление состоянием и интеграцию API \u2014 в сотрудничестве с бэкенд-разработчиками.' },
        ],
      },
      services: {
        title: 'Услуги',
        subtitle: 'Что я могу сделать для вашего проекта',
        s1Title: 'Современные веб-макеты',
        s1Desc: 'Красивые, семантические HTML-структуры с Flexbox, Grid, кастомными свойствами и адаптивными брейкпоинтами.',
        s2Title: 'Адаптивный UI-дизайн',
        s2Desc: 'Интерфейсы mobile-first на Tailwind CSS и React. Каждый компонент проверен на всех устройствах.',
        s3Title: 'Производительность и анимации',
        s3Desc: 'Плавные 60fps анимации с Framer Motion, оптимизированный рендеринг и чистая архитектура компонентов.',
      },
      footer: { copyright: 'Все права защищены.', builtWith: 'Создано с заботой Фаридуном Абдуразаковым' },
    },
  },
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
    detection: {
      order: ['localStorage', 'navigator'],
      caches: ['localStorage'],
      lookupLocalStorage: 'portfolio-language',
    },
  });

export default i18n;
